version: "3.9"

services:
  minio:
    image: minio/minio
    container_name: mystorage-minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"

    volumes:
      - minio_data:/data

    restart: unless-stopped

volumes:
  minio_data:

